name: Apply for DICE jobs daily

on:
  schedule:
    - cron: "0 12 * * *"  # Runs at 6 AM CST (12 PM UTC)
    - cron: "0 16 * * *"  # Runs at 10 AM CST (4 PM UTC)
  workflow_dispatch:
    inputs:
      job_role:
        description: "Enter the job role to search"
        required: false
        default: "java full stack developer"
      date_posted:
        description: "Select the job date posted"
        required: false
        default: "Today"
        type: choice
        options:
          - "Today"
          - "Last 3 Days"
          - "Last 7 Days"
          - "Any Date"

jobs:
  dice_job_application:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Run TestNG tests
        run: mvn test

      - name: Upload TestNG Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testng-results
          path: target/test-*.xml
          retention-days: 7

      - name: Upload Job Applications Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: job-applications-report
          path: xslx-reports/job_applications.xlsx
          retention-days: 7
