name: Apply for DICE jobs daily

on:
  schedule:
    - cron: "0 11 * * *"    # Runs at 6:00 AM CDT
    - cron: "30 15 * * *"   # Runs at 10:30 AM CDT
  workflow_dispatch:
    inputs:
      job_role:
        description: "Enter the job role to search"
        required: false
        default: "qa engineer"
      date_posted:
        description: "Select the job date posted"
        required: false
        default: "Today"
        type: choice
        options:
          - "Today"
          - "Last 3 Days"
          - "Last 7 Days"
          - "Any Date"

jobs:
  dice_job_application:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven Dependencies
        run: mvn install -DskipTests

      - name: Run TestNG Tests with Retry
        run: |
          MAX_RETRIES=2
          COUNT=0
          until mvn test; do
            COUNT=$((COUNT+1))
            if [ "$COUNT" -ge "$MAX_RETRIES" ]; then
              echo "❌ Test failed after $MAX_RETRIES attempts"
              exit 1
            fi
            echo "⚠️ Test failed... retrying ($COUNT/$MAX_RETRIES)"
            sleep 10
          done
        env:
          EMAIL: ${{ secrets.DICE_EMAIL }}
          PASSWORD: ${{ secrets.DICE_PASSWORD }}

      - name: Upload Job Applications Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: job-applications-report
          path: xslx-reports/job_applications.xlsx
          retention-days: 7
